In [2]:
import numpy as np
import pandas as pd

In [3]:
data={
    'Empid':[x for x in range(101,111)],
    'Empname':['Raj','Raman','Rahul','Anu',np.nan,'Aman','Sonu','Shiva','Ram','Anu'],
    'EmpSalary':[23445,78898,np.nan,89897,23345,67856,45433,78978,np.nan,45786]
    }

In [4]:
df=pd.DataFrame(data)

In [12]:
df

   Empid Empname  EmpSalary
0    101     Raj    23445.0
1    102   Raman    78898.0
2    103   Rahul        NaN
3    104     Anu    89897.0
4    105     NaN    23345.0
5    106    Aman    67856.0
6    107    Sonu    45433.0
7    108   Shiva    78978.0
8    109     Ram        NaN
9    110     Anu    45786.0

In [10]:
df.isnull().sum()

Empid        0
Empname      1
EmpSalary    2
dtype: int64

df.fillna() = Jahan NaN (missing value) ho, wahan apni di hui value bhar deta hai.

👉 Yaad rakhne ki trick:

fill = bhar do
na = missing value (NaN)
Example:
df.fillna(0)

➡️ Saare NaN ki jagah 0 aa jayega.

Example:
df.fillna("Unknown")

➡️ Saare NaN ki jagah "Unknown" aa jayega.

One-line definition:

df.fillna() = DataFrame me missing values (NaN) ko kisi specified value se replace karta hai.

In [13]:
df.fillna('No Name')

   Empid  Empname EmpSalary
0    101      Raj   23445.0
1    102    Raman   78898.0
2    103    Rahul   No Name
3    104      Anu   89897.0
4    105  No Name   23345.0
5    106     Aman   67856.0
6    107     Sonu   45433.0
7    108    Shiva   78978.0
8    109      Ram   No Name
9    110      Anu   45786.0

In [8]:
df.dropna()

   Empid Empname  EmpSalary
0    101     Raj    23445.0
1    102   Raman    78898.0
3    104     Anu    89897.0
5    106    Aman    67856.0
6    107    Sonu    45433.0
7    108   Shiva    78978.0
9    110     Anu    45786.0

df.dropna() = Jis row ya column me NaN (missing value) ho, usko hata deta hai.

👉 Yaad rakhne ki trick:

drop = hata do
na = missing value (NaN)
Example:
df.dropna()

➡️ NaN wali rows delete ho jayengi.

Agar columns delete karne ho:
df.dropna(axis=1)

➡️ NaN wale columns delete ho jayenge.

One-line definition:

df.dropna() = DataFrame se missing values (NaN) wali rows/columns ko remove karta hai.

Handles Missing Values
Text-Replace with another value(No Name,Not Found,Not Available,Example etc)
    -if data is repeated (mostly replace with mode(most_frequent_item))

Numerical-if data point has connection or relation with another data point/column Try to Repair.
        - if data has no relation with another data point/column (replace it with mean / mode).
Qty price NetAmount
2   10      20
5           25              Try to Repair 25/5=5(prices)
7   5       35

Age
34
45
                            try to replace this value with mean(mostlyunique values in column)
56

In [15]:
newdf=df.fillna('Not Found')

In [16]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     object
 2   EmpSalary  10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

we can not calculate newdf.Empsalary.sum() or newdf.Empsalary.mean()
beacause of object/str type
we should replace values in numerical with numerical data points.

In [17]:
newdf=df.copy()

In [18]:
newdf

   Empid Empname  EmpSalary
0    101     Raj    23445.0
1    102   Raman    78898.0
2    103   Rahul        NaN
3    104     Anu    89897.0
4    105     NaN    23345.0
5    106    Aman    67856.0
6    107    Sonu    45433.0
7    108   Shiva    78978.0
8    109     Ram        NaN
9    110     Anu    45786.0

In [19]:
newdf.Empname=newdf.Empname.fillna('No Name')

In [20]:
newdf

   Empid  Empname  EmpSalary
0    101      Raj    23445.0
1    102    Raman    78898.0
2    103    Rahul        NaN
3    104      Anu    89897.0
4    105  No Name    23345.0
5    106     Aman    67856.0
6    107     Sonu    45433.0
7    108    Shiva    78978.0
8    109      Ram        NaN
9    110      Anu    45786.0

In [21]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     object
 2   EmpSalary  8 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes

In [22]:
newdf.EmpSalary.mean()

np.float64(56704.75)

In [23]:
newdf.EmpSalary=newdf.EmpSalary.fillna(0)

In [24]:
newdf

   Empid  Empname  EmpSalary
0    101      Raj    23445.0
1    102    Raman    78898.0
2    103    Rahul        0.0
3    104      Anu    89897.0
4    105  No Name    23345.0
5    106     Aman    67856.0
6    107     Sonu    45433.0
7    108    Shiva    78978.0
8    109      Ram        0.0
9    110      Anu    45786.0

In [25]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     object
 2   EmpSalary  10 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes

In [26]:
newdf.EmpSalary.sum()

np.float64(453638.0)

In [27]:
newdf.EmpSalary.mean()

np.float64(45363.8)

In [28]:
newdf=df.copy()

In [29]:
newdf

   Empid Empname  EmpSalary
0    101     Raj    23445.0
1    102   Raman    78898.0
2    103   Rahul        NaN
3    104     Anu    89897.0
4    105     NaN    23345.0
5    106    Aman    67856.0
6    107    Sonu    45433.0
7    108   Shiva    78978.0
8    109     Ram        NaN
9    110     Anu    45786.0

In [30]:
newdf.EmpSalary=newdf.EmpSalary.fillna(newdf.EmpSalary.mean())

In [31]:
newdf

   Empid Empname  EmpSalary
0    101     Raj   23445.00
1    102   Raman   78898.00
2    103   Rahul   56704.75
3    104     Anu   89897.00
4    105     NaN   23345.00
5    106    Aman   67856.00
6    107    Sonu   45433.00
7    108   Shiva   78978.00
8    109     Ram   56704.75
9    110     Anu   45786.00

In [32]:
newdf.EmpSalary.mean()

np.float64(56704.75)

In [33]:
newdf=df.copy()

In [34]:
df.columns

Index(['Empid', 'Empname', 'EmpSalary'], dtype='object')

In [38]:
for col in df.columns:
    print(col,df[col].dtype,df[col].isnull().sum())

Empid int64 0
Empname object 1
EmpSalary float64 2

In [40]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        print(col,df[col].dtype,df[col].isnull().sum())

Empname object 1
EmpSalary float64 2

In [44]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        if df[col].dtype in [object,str]:
            print(col,'\t',df[col].dtype,'\t',df[col].isnull().sum(),df[col].mode()[0])
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            print(col,'\t',df[col].dtype,'\t',df[col].isnull().sum().mean())
            df[col]=df[col].fillna(df[col].mean())

Empname 	 object 	 1 Anu
EmpSalary 	 float64 	 2.0

for col in df.columns:

➡️ DataFrame ke har column par loop chalao.

if df[col].isnull().sum() > 0:

➡️ Agar column me missing values (NaN) hain.

if df[col].dtype in [object, str]:

➡️ Agar column text (string) type ka hai.

df[col] = df[col].fillna(df[col].mode()[0])

➡️ Missing values ko Mode (sabse zyada aane wali value) se fill karo.

else:

➡️ Warna (numeric column hai).

df[col] = df[col].fillna(df[col].mean())

➡️ Missing values ko Mean (average) se fill karo.

One-line Trick 🚀

Text Column ➜ Mode se Fill

Number Column ➜ Mean se Fill

In [45]:
df.isnull().sum()

Empid        0
Empname      0
EmpSalary    0
dtype: int64

Lec 74

In [46]:
import numpy as np
import pandas as pd

In [47]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\dell\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [53]:
dataset=pd.read_excel(r"C:\Users\dell\Downloads\Financial Sample.xlsx")

In [54]:
dataset.shape

(700, 16)

In [57]:
df.head

<bound method NDFrame.head of    Empid Empname  EmpSalary
0    101     Raj   23445.00
1    102   Raman   78898.00
2    103   Rahul   56704.75
3    104     Anu   89897.00
4    105     Anu   23345.00
5    106    Aman   67856.00
6    107    Sonu   45433.00
7    108   Shiva   78978.00
8    109     Ram   56704.75
9    110     Anu   45786.00>