In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\dell\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
df=pd.read_excel(r"C:\Users\dell\Downloads\Financial Sample.xlsx")

In [12]:
dataset.shape

(700, 16)

In [9]:
dataset.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [14]:
df.Product

0      Carretera
1      Carretera
2      Carretera
3      Carretera
4      Carretera
         ...
695     Amarilla
696     Amarilla
697      Montana
698        Paseo
699          VTT
Name: Product, Length: 700, dtype: object

In [15]:
df.Product.unique()

array(['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla'],
      dtype=object)

In [16]:
df.Product.value_counts()

Product
Paseo        202
Velo         109
VTT          109
Amarilla      94
Montana       93
Carretera     93
Name: count, dtype: int64

In [ ]:
#Segment is column:
df.Segment.unique()

array(['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
       'Small Business'], dtype=object)

In [19]:
df.Segment.value_counts()

Segment
Government          300
Midmarket           100
Channel Partners    100
Enterprise          100
Small Business      100
Name: count, dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        647 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [23]:
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          53
Units Sold              0
Manufacturing Price     0
Sale Price              0
Gross Sales             0
Discounts               0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [24]:
for col in df.columns:
    print(col)

Segment
Country
Product
Discount Band
Units Sold
Manufacturing Price
Sale Price
Gross Sales
Discounts
 Sales
COGS
Profit
Date
Month Number
Month Name
Year

In [28]:
#print missing value columns names:
for col in df.columns:
    if df[col].isnull().sum()>0:
        print(col,'\t',df[col].isnull().sum(),'\t',df[col].dtype)

Discount Band 	 53 	 object

In [ ]:
#fill missing values numerical with mean(average) and categorical/text with mode(most_frequent)
for col in df.columns:
    if df[col].isnull().sum()>0:
        if df[col].dtype in [object,str]:
            print(col,'\t',df[col].isnull().sum(),'\t',df[col].dtype,'\t',df[col].mode()[0])
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            print(col,'\t',df[col].isnull().sum(),'\t',df[col].dtype,'\t',df[col].mean())
            df[col]=df[col].fillna(round(df[col].mean(),2))
# Column ka average (mean) nikalo
#➡️ Usko 2 decimal places tak round karo
#➡️ Jahan NaN hai, wahan woh average bhar do.

#🧠 Short trick:

#NaN → Mean → Round(2) → Fill

Discount Band 	 53 	 object 	 High

for col in df.columns:

➡️ Har column ko ek-ek karke dekho.

if df[col].isnull().sum() > 0:

➡️ Kya column mein NaN hai?

if df[col].dtype in [object, str]:

➡️ Agar column text hai → uski information print karo.

print(...)

➡️ Column name + NaN count + data type + Mode dikhao.

else:
    print(...)

➡️ Agar number column hai → Column name + NaN count + data type dikhao.

🧠 Ek line mein:

Har column check karo → NaN hai? → Text hai to Mode bhi dikhao, Number hai to basic information dikhao.

In [35]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [36]:
#Re clean the dataset
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#handle missing values of text/object column:
for col in df.columns:
    if df[col].dtype in [object , str]:
        print(col , '\t' ,df[col].isnull().sum(),'\t Mode :',df[col].mode()[0])
        df[col]=df[col].fillna(df[col].mode()[0])

Segment 	 0 	 Mode : Government
Country 	 0 	 Mode : Canada
Product 	 0 	 Mode : Paseo
Discount Band 	 0 	 Mode : High
Month Name 	 0 	 Mode : October

In [42]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [47]:
#handle missing value numerical column
for col in df.select_dtypes(include=np.number).columns:
    if df[col].isnull().sum() > 0:
        print(col, '\t', df[col].dtype, '\t',
              df[col].isnull().sum(), '\t Mean :',
              round(df[col].mean(), 2))

        df[col] = df[col].fillna(round(df[col].mean(), 2))

In [48]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [49]:
df.Product.value_counts()

Product
Paseo        202
Velo         109
VTT          109
Amarilla      94
Montana       93
Carretera     93
Name: count, dtype: int64

In [50]:
df.Product.value_counts()

Product
Paseo        202
Velo         109
VTT          109
Amarilla      94
Montana       93
Carretera     93
Name: count, dtype: int64

In [56]:
df.groupby('Product')['Profit'].sum()

Product
Amarilla     2814104.060
Carretera    1826804.885
Montana      2114754.880
Paseo        4797437.950
VTT          3034608.020
Velo         2305992.465
Name: Profit, dtype: float64

In [55]:
#GROUPBY
df.groupby('Product')['Profit'].sum().reset_index()

     Product       Profit
0   Amarilla  2814104.060
1  Carretera  1826804.885
2    Montana  2114754.880
3      Paseo  4797437.950
4        VTT  3034608.020
5       Velo  2305992.465

In [68]:
df.groupby('Country').agg({
    ' Sales': 'sum',
    'Profit': 'sum'
})

                                 Sales       Profit
Country
Canada                    2.488765e+07  3529228.885
France                    2.435417e+07  3781020.780
Germany                   2.350534e+07  3680388.820
Mexico                    2.094935e+07  2907523.110
United States of America  2.502983e+07  2995540.665

In [76]:
pbc=df.groupby('Country').agg({
    ' Sales': 'sum',
    'Profit': 'sum'
}).reset_index()

In [75]:
pbc

                    Country         Sales       Profit
0                    Canada  2.488765e+07  3529228.885
1                    France  2.435417e+07  3781020.780
2                   Germany  2.350534e+07  3680388.820
3                    Mexico  2.094935e+07  2907523.110
4  United States of America  2.502983e+07  2995540.665

In [61]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,High,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,High,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,High,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,High,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,High,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [78]:
pbc['ProfitMargin'] = pbc['Profit']/pbc['Sales'] * 100

KeyError: 'Sales'

In [ ]:
pbc['TotalProfit%age']=pbc['Profit']/pbc['profit'].sum*100

KeyError: 'profit'