In [1]:
a=10

In [2]:
b=20

In [3]:
c=20

In [4]:
print(c)

20

In [37]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\dell\appdata\roaming\python\python312\site-packages (2.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

!pip install numpy

In [10]:
import numpy as np

In [7]:
numpy.__version__

'2.2.3'

numpy => numerical in python
numpy is very powerful library for mathematical operations/computation
numpy is use to create arrays
array is a collection of homogeneous(same data type) elements
ways to create an array
array,arrange,linspace

In [11]:
arr=np.array([34,76,789,89])
arr

array([ 34,  76, 789,  89])

In [13]:
arr=np.array([34,57.78,'Aman',35,True,3+8j])
arr

array(['34', '57.78', 'Aman', '35', 'True', '(3+8j)'], dtype='<U64')

In [14]:
arr=np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr=np.arange(2,21,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

linspace() = "Mujhe start aur end ke beech itne equally spaced numbers de do."

Syntax:

np.linspace(start, stop, num)
start = Kahan se start
stop = Kahan tak
num = Kitne numbers chahiye
Example
import numpy as np

print(np.linspace(1, 5, 5))

Output:

[1. 2. 3. 4. 5.]
print(np.linspace(1, 5, 3))

Output:

[1. 3. 5.]
🎯 Memory Trick

np.arange() → Step batao.

np.arange(1, 10, 2)
# 1 3 5 7 9

np.linspace() → Total numbers batao.

np.linspace(1, 10, 5)
# 1.00 3.25 5.50 7.75 10.00
🧠 One-line Formula

linspace() = "Equal gap wale fixed number of values." 🚀

In [16]:
#Linspace(start,stop,number_of_elements) (start,stop both will include)
arr=np.linspace(0.5,5,10)
arr

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [17]:
arr=np.arange(65,91,1)
arr

array([65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90])

In [23]:
np.array(map(lambda val:chr(val),arr))

TypeError: iteration over a 0-d array

In [24]:
arr

array(<map object at 0x0000028DDDAB2BF0>, dtype=object)

In [29]:
arr = np.array([65, 66, 67])
result = np.array(list(map(lambda val: chr(val), arr)))
arr
print(arr)

[65 66 67]

In [30]:
result = np.array(list(map(chr, arr)))
print(result)

['A' 'B' 'C']

In [31]:
arr = np.arange(65, 91)   # ASCII values from 65 to 90
result = np.array([chr(x) for x in arr])
print(result)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']

Dimension
0thD,1D,2D,3D--------ND

In [32]:
#0D
arr=np.array(34)
print(arr)
print(arr.shape)
print(arr.ndim)

34
()
0

In [34]:
#1D
arr=np.array([34,56,78])
print(arr)
print(arr.shape)
print(arr.ndim)

[34 56 78]
(3,)
1

In [35]:
#2d
arr=np.array([[34,45,76],[34,56,67],[65,78,89]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[34 45 76]
 [34 56 67]
 [65 78 89]]
(3, 3)
2

In [36]:
#3D
arr=np.array([[[34,45,67],[33,54,56]],[[34,45,67],[33,54,56]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[34 45 67]
  [33 54 56]]

 [[34 45 67]
  [33 54 56]]]
(2, 2, 3)
3

In [38]:
#identify,eye,full,one,Zeros,zeroslike,ones_like

In [39]:
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

Pandas is an open-source Python library used primarily for data manipulation, cleaning, and analysis. It provides fast, flexible data structures designed to make working with structured (tabular) data intuitive and efficient, acting essentially like Excel or SQL databases inside your code.
Pandas in the Easiest Way (Step by Step)
Step 1: Import Pandas
import pandas as pd

👉 pd = short name of pandas.

Step 2: Two Main Data Structures
1. Series (1 Column)
s = pd.Series([10, 20, 30])
print(s)

Think of it as one Excel column.

2. DataFrame (Rows + Columns)
df = pd.DataFrame({
    "Name": ["Aman", "Rahul"],
    "Age": [20, 22]
})
print(df)

Think of it as an Excel sheet.

6 Main Uses of Pandas
1. Load & Save Data

Read data:

df = pd.read_csv("data.csv")

Save data:

df.to_excel("output.xlsx", index=False)

📌 Remember:
read_* = Load
to_* = Save

2. Clean Data

Remove missing values

df.dropna()

Fill missing values

df.fillna(0)

Remove duplicate rows

df.drop_duplicates()

📌 Remember:

drop = Remove
fill = Fill
3. Filter Data

Age > 25

df[df["Age"] > 25]

Select columns

df[["Name", "Age"]]

📌 Remember:
Condition inside []

4. Group Data

Average salary by department

df.groupby("Department")["Salary"].mean()

📌 Formula:

groupby() → mean()
5. Statistics
df.describe()

Shows:

Count
Mean
Min
Max
Quartiles

📌 One command = Full summary

6. Date & Time

Convert text to date

df["Date"] = pd.to_datetime(df["Date"])

Monthly total

df.resample("M", on="Date").sum()

📌 Remember:

to_datetime() = Convert to date
resample() = Group by time
Pandas Ecosystem
Library	Work
NumPy	Fast calculations
Pandas	Data cleaning & analysis
Matplotlib	Charts
Seaborn	Beautiful charts
Scikit-Learn	Machine Learning
Polars / PySpark	Very large datasets
Easy Flow to Remember
Import Pandas
      ↓
Load Data
      ↓
View Data
      ↓
Clean Data
      ↓
Filter Data
      ↓
Group Data
      ↓
Statistics
      ↓
Visualization
      ↓
Machine Learning
Super Short Revision (Exam Ready)
Series → 1 Column
DataFrame → Table (Rows + Columns)
read_csv() → Load
to_excel() → Save
dropna() → Remove null values
fillna() → Fill null values
drop_duplicates() → Remove duplicates
groupby() → Group data
describe() → Statistics
to_datetime() → Convert to date
resample() → Time-based analysis

Memory Trick:
L C F G S T → Load → Clean → Filter → Group → Statistics → Time Analysis 🚀

In [40]:
arr=np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
arr=np.ones((4,4),dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
arr=np.zeros((3,3),dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
arr=np.full((5,5),9)
arr

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [46]:
arr=np.full((3,4),5)
arr

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [50]:
onearray=np.ones((3,6),dtype=int)
onearray

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [51]:
arr=np.zeros_like(onearray)
arr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [52]:
arr=np.ones_like(onearray)
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [53]:
arr=np.identity(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
arr=np.identity(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [58]:
arr=np.eye(4,5 , dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [59]:
#blank
np.nan

nan

In [60]:
np.number

numpy.number

In [ ]:
#works on all type of numerical data type
np.number=int

In [62]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\dell\appdata\roaming\python\python312\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
#required for loading an excel file:
pip install openpyxl

SyntaxError: invalid syntax (2941520347.py, line 2)

In [65]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\dell\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\dell\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
import pandas

<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.number size changed, may indicate binary incompatibility. Expected 16 from C header, got 24 from PyObject
<frozen importlib._bootstrap>:488: RuntimeWarning: numpy.number size changed, may indicate binary incompatibility. Expected 16 from C header, got 24 from PyObject

In [67]:
pandas.__version__

'2.2.3'

In [68]:
import pandas as pd

In [69]:
pd.__version__

'2.2.3'

pandas is use to work on dataframe(2d Excel,json,db etc) and Series(1D).
it is also use to load data into environment or use to read dataset.
it is also use to transform ,clean and feature engineering(for preprocessing).

In [70]:
data={
    'Empid':[x for x in range(101,111)],
    'Empname':['Raj','Raman','Rahul','Anu','Manu','Aman','Sonu','Shiva','Ram','Anu'],
    'Empsalary':[23445,78898,46665,89897,23345,67856,45433,78978,56555,45786]
    }

In [71]:
print(data)

{'Empid': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'Empname': ['Raj', 'Raman', 'Rahul', 'Anu', 'Manu', 'Aman', 'Sonu', 'Shiva', 'Ram', 'Anu'], 'Empsalary': [23445, 78898, 46665, 89897, 23345, 67856, 45433, 78978, 56555, 45786]}

In [72]:
dataset=pd.DataFrame(data)

In [73]:
dataset

  Empid Empname Empsalary
0   101     Raj     23445
1   102   Raman     78898
2   103   Rahul     46665
3   104     Anu     89897
4   105    Manu     23345
5   106    Aman     67856
6   107    Sonu     45433
7   108   Shiva     78978
8   109     Ram     56555
9   110     Anu     45786

In [ ]:
#Head shows top 5 rows of dataset
dataset.head()

  Empid Empname Empsalary
0   101     Raj     23445
1   102   Raman     78898
2   103   Rahul     46665
3   104     Anu     89897
4   105    Manu     23345

In [ ]:
#tail show bottom 5 rows of datasets:
dataset.tail()

  Empid Empname Empsalary
5   106    Aman     67856
6   107    Sonu     45433
7   108   Shiva     78978
8   109     Ram     56555
9   110     Anu     45786

In [76]:
dataset.tail(3)

  Empid Empname Empsalary
7   108   Shiva     78978
8   109     Ram     56555
9   110     Anu     45786

In [79]:
dataset.Empname

0      Raj
1    Raman
2    Rahul
3      Anu
4     Manu
5     Aman
6     Sonu
7    Shiva
8      Ram
9      Anu
Name: Empname, dtype: object

In [80]:
dataset['Empid']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: Empid, dtype: int64

In [81]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    10 non-null     object
 2   Empsalary  10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [91]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

In [90]:
print(type(dataset))
print(dataset.head())
print(dataset.dtypes)

<class 'pandas.core.frame.DataFrame'>
  Empid Empname Empsalary
0   101     Raj     23445
1   102   Raman     78898
2   103   Rahul     46665
3   104     Anu     89897
4   105    Manu     23345
Empid         int64
Empname      object
Empsalary     int64
dtype: object

In [89]:
dataset.describe()
#alternate to check data info 
print(type(dataset))
print(dataset.head())
print(dataset.dtypes)

NotImplementedError: int64

In [93]:
dataset.Empsalary

0    23445
1    78898
2    46665
3    89897
4    23345
5    67856
6    45433
7    78978
8    56555
9    45786
Name: Empsalary, dtype: int64

In [94]:
dataset.Empsalary.sum()

np.int64(556858)

In [95]:
dataset.Empsalary.mean()

np.float64(55685.8)

In [97]:
dataset.Empname.value_counts()

Empname
Anu      2
Raj      1
Raman    1
Rahul    1
Manu     1
Aman     1
Sonu     1
Shiva    1
Ram      1
Name: count, dtype: int64

In [98]:
dataset.Empname.mode()

0    Anu
Name: Empname, dtype: object

In [99]:
dataset.Empname.mode()[0]

'Anu'

In [101]:
dataset.Empname.mode()[1]

KeyError: 1

In [102]:
import numpy as np

In [103]:
data={
    'Empid':[x for x in range(101,111)],
    'Empname':['Raj','Raman','Rahul','Anu',np.nan,'Aman','Sonu','Shiva','Ram','Anu'],
    'Empsalary':[23445,78898,np.nan,89897,23345,67856,45433,78978,np.nan,45786]
    }

In [104]:
df=pd.DataFrame(data)

In [105]:
df

  Empid Empname Empsalary
0   101     Raj   23445.0
1   102   Raman   78898.0
2   103   Rahul       NaN
3   104     Anu   89897.0
4   105     NaN   23345.0
5   106    Aman   67856.0
6   107    Sonu   45433.0
7   108   Shiva   78978.0
8   109     Ram       NaN
9   110     Anu   45786.0

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      10 non-null     int64
 1   Empname    9 non-null      object
 2   Empsalary  8 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes

In [107]:
df.isnull()

   Empid  Empname  Empsalary
0  False    False      False
1  False    False      False
2  False    False       True
3  False    False      False
4  False     True      False
5  False    False      False
6  False    False      False
7  False    False      False
8  False    False       True
9  False    False      False

In [108]:
df.isnull().sum()

Empid        0
Empname      1
Empsalary    2
dtype: int64

In [109]:
df.isnull().sum().sum()

np.int64(3)

In [112]:
df.shape

(10, 3)

In [115]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])
print("Values:",df.shape[0]*df.shape[1])

Rows: 10
Columns: 3
Values: 30

In [122]:
#missing data in overall dataset
print("Missing dataset:",df.isnull().sum().sum()/(df.shape[0]*df.shape[1])*100,"%")

Missing dataset: 10.0 %

In [119]:
missing_percentage = (df.isnull().sum().sum() / (df.shape[0] * df.shape[1])) * 100
print("Missing Dataset: ", missing_percentage, "%")

Missing Dataset:  10.0 %