In [4]:
import pandas as pd
import numpy as np

In [6]:
pip install openpyxl
#python -m pip install openpyxl

SyntaxError: invalid syntax (1581040236.py, line 1)

In [8]:
cus = pd.read_excel(
    r"C:\Users\dell\Downloads\Ecomm (1).xlsx",
    sheet_name="CustomerDetail"
)

In [9]:
cus.shape

(24, 12)

In [10]:
order=pd.read_excel(r"C:\Users\dell\Downloads\Ecomm (1).xlsx",sheet_name="Jan")

In [11]:
order.shape

(1952, 8)

In [12]:
cus.head(2)

,CustomerID,CustomerID.1,Order Date,Month,MonthName,DateInText,Customer Name,State or Province,City,Gender,Gender.1,Gender.2
0,CUS7253,7253,2015-01-07,1,Jan,01/07/2015,Bonnie Potter,Washington,Anacortes,M,1,MALE
1,CUS4875,4875,2015-06-13,6,Jun,06/13/2015,Ronnie Proctor,California,San Gabriel,F,0,FEMALE

In [13]:
cus=cus.drop(columns=['CustomerID','Month','MonthName','DateInText','Gender','Gender.1'])

In [14]:
cus = cus.rename(columns={'CustomerID.1':'CustomerID','Gender.2':'Gender'})

In [15]:
cus.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [16]:
cus.isnull().sum()

CustomerID           0
Order Date           0
Customer Name        0
State or Province    0
City                 0
Gender               0
dtype: int64

In [17]:
cus = cus.dropna()

In [18]:
cus.duplicated().sum()

np.int64(0)

In [19]:
cus = cus.drop_duplicates()

In [20]:
cus.shape

(24, 6)

In [21]:
cus.head()

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE
2,2748,2015-02-15,Marcus Dunlap,New Jersey,Roselle,MALE
3,4565,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE
4,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE

In [22]:
order.head()

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card
2,90192,2583,208.56,-53.8096,22,Furniture,Office Furnishings,Credit Card
3,86838,8372,1259.04,803.4705,16,Furniture,Office Furnishings,Credit Card
4,86838,6458,22.96,-24.0300,7,Office Supplies,Pens & Art Supplies,Credit Card

In [23]:
order.isnull().sum()

Order ID                0
CustomerID              0
Amount                  0
Profit                  0
Quantity ordered new    0
Product Category        0
Product Sub-Category    0
Payment Mode            0
dtype: int64

In [24]:
order = order.dropna()

In [25]:
order.Profit.sum()

np.float64(224114.64183714997)

In [26]:
order['Product Category'].unique()

array(['Office Supplies', 'Furniture', 'Technology'], dtype=object)

In [27]:
order.groupby('Product Category')['Profit'].sum()

Product Category
Furniture          59249.445936
Office Supplies    89562.039537
Technology         75303.156364
Name: Profit, dtype: float64

In [28]:
order.groupby('Product Category').agg({'Profit':'sum'})

                        Profit
Product Category
Furniture         59249.445936
Office Supplies   89562.039537
Technology        75303.156364

In [29]:
order.groupby('Product Category').agg({'Profit':'sum'}).reset_index()

  Product Category        Profit
0        Furniture  59249.445936
1  Office Supplies  89562.039537
2       Technology  75303.156364

In [30]:
pbp = order.groupby('Product Category').agg({'Profit':'sum'}).reset_index()

In [31]:
pbp

  Product Category        Profit
0        Furniture  59249.445936
1  Office Supplies  89562.039537
2       Technology  75303.156364

In [32]:
#Merge Dataset
df = pd.merge(cus, order, on='CustomerID', how='inner')

In [33]:
df.shape

(1952, 13)

In [34]:
df.head()

,CustomerID,Order Date,Customer Name,State or Province,City,Gender,Order ID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,88522,11.36,4.560000,4,Office Supplies,Pens & Art Supplies,Credit Card
1,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,90669,94.27,105.678000,11,Office Supplies,"Scissors, Rulers and Trimmers",Credit Card
2,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,86297,285.84,-2177.986096,9,Furniture,Tables,Credit Card
3,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,89320,1982.14,1372.630800,31,Furniture,Office Furnishings,Credit Card
4,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,90910,7149.87,4637.407200,13,Technology,Copiers and Fax,Credit Card

In [35]:
df.groupby("State or Province").agg({"Profit":'sum'}).reset_index()

  State or Province        Profit
0        California  31886.448316
1         Minnesota  34330.365504
2           Montana  15291.345669
3          New York  98143.568974
4            Oregon  44462.913374

In [36]:
df.groupby("State or Province").agg({"Amount":'sum',"Profit":'sum'}).reset_index()

  State or Province     Amount        Profit
0        California  504316.36  31886.448316
1         Minnesota  127080.87  34330.365504
2           Montana  270342.99  15291.345669
3          New York  840499.42  98143.568974
4            Oregon  242224.79  44462.913374

In [37]:
pbs=df.groupby("State or Province").agg({"Amount":'sum',"Profit":'sum'}).reset_index()

In [38]:
pbs

  State or Province     Amount        Profit
0        California  504316.36  31886.448316
1         Minnesota  127080.87  34330.365504
2           Montana  270342.99  15291.345669
3          New York  840499.42  98143.568974
4            Oregon  242224.79  44462.913374

In [39]:
pbs.Profit = pbs.Profit.map(lambda val:round(val,2))

In [40]:
pbs

  State or Province     Amount    Profit
0        California  504316.36  31886.45
1         Minnesota  127080.87  34330.37
2           Montana  270342.99  15291.35
3          New York  840499.42  98143.57
4            Oregon  242224.79  44462.91