In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel(r"C:\Users\dell\Downloads\Financial Sample.xlsx").bfill()

In [3]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount Band        700 non-null    object
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    int64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(6), int64(4), object(5)
memory usage: 87.6+ KB

In [5]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

df.select_dtypes(include='object') ka simple meaning hai:

DataFrame me se sirf text/string wale columns ko select karo.

Breakdown:
df.select_dtypes(include='object')
df → aapka DataFrame
.select_dtypes() → columns ko unke data type ke basis par select karta hai.
include='object' → sirf object datatype wale columns select karega.
Pandas mein object generally text/string data ko represent karta hai.
Real-life example

Agar df mein ye columns hain:

Country	Sales	Product	Units Sold
India	5000	Laptop	10
USA	7000	Mobile	20

To:

df.select_dtypes(include='object')

Output mein sirf:

Country	Product
India	Laptop
USA	Mobile
⭐ Why useful?

Data cleaning mein bahut useful hai. For example, agar aap text columns ke missing values ko mode se fill karna chahte ho:

obj_cols = df.select_dtypes(include='object').columns

Ab obj_cols mein sirf text columns ke names aa jayenge.

Yaad rakhna:
select_dtypes = datatype ke basis par columns select karna.

In [13]:
df.select_dtypes(include='object').columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Month Name'], dtype='object')

In [9]:
for col in df.select_dtypes(include='object').columns:
    print(col,":",df[col].unique())

Segment : ['Government' 'Midmarket' 'Channel Partners' 'Enterprise' 'Small Business']
Country : ['Canada' 'Germany' 'France' 'Mexico' 'United States of America']
Product : ['Carretera' 'Montana' 'Paseo' 'Velo' 'VTT' 'Amarilla']
Discount Band : ['Low' 'Medium' 'High']
Month Name : ['January' 'June' 'December' 'March' 'July' 'August' 'September' 'October'
 'February' 'November' 'April' 'May']

In [14]:
#Ordinal Encoding
df['Discount Band'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [15]:
list(df['Discount Band'].unique()).index('High')

2

df['Discount Band'] = df['Discount Band'].map(
    lambda val: list(df['Discount Band'].unique()).index(val)
)
🎯 Main purpose

Discount Band ke text values ko numbers mein convert karna.

Maan lo:

Discount Band
--------------
None
Low
Medium
High
Low
High

Pehle:

df['Discount Band'].unique()

maan lo output:

['None', 'Low', 'Medium', 'High']
Ab poori line ka breakdown:

1. unique()

df['Discount Band'].unique()

Unique values nikalega:

['None', 'Low', 'Medium', 'High']

2. list()

list(df['Discount Band'].unique())

Array ko Python list mein convert karega:

['None', 'Low', 'Medium', 'High']

3. .index(val)

list(...).index(val)

Value ka position/index number find karega.

Example:

None    → 0
Low     → 1
Medium  → 2
High    → 3

4. lambda val:

lambda val: ...

Har value ko ek-ek karke val mein lega.

For example:

val = 'Low'

Then:

list(...).index('Low')

Output:

1

5. .map()

df['Discount Band'].map(...)

Column ki har value par ye lambda function apply karega.

Final result

Before:

None
Low
Medium
High
Low

After:

0
1
2
3
1
⚠️ Important

Ye label encoding jaisa conversion hai, lekin numbers ka actual mathematical meaning nahi hai.

For example, High = 3 ka matlab ye nahi ki High ki value mathematically Medium (2) se exactly 1 zyada hai.

Agar aapka purpose Machine Learning ke liye categorical encoding hai, to LabelEncoder ya OrdinalEncoder bhi use kiya ja sakta hai.

In [16]:
#Perform Ordinal Encoding (Mannual -> Algorithm)
df['Discount Band']=df['Discount Band'].map(lambda val:list(df['Discount Band'].unique()).index(val))

In [17]:
df['Discount Band']

0      0
1      0
2      0
3      0
4      0
      ..
695    2
696    2
697    2
698    2
699    2
Name: Discount Band, Length: 700, dtype: int64

In [18]:
df['Discount Band'].unique()

array([0, 1, 2])

In [24]:
df=pd.read_excel(r"C:\Users\dell\Downloads\Financial Sample.xlsx").bfill()

In [20]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [32]:
oe=OrdinalEncoder()

In [28]:
df['Discount Band'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [29]:
oe=OrdinalEncoder(categories=['Low','Medium','High'])

df['Discount Band'] = oe.fit_transform(df[['Discount Band']])

Yahan double square brackets [[ ]] isliye use kiye hain kyunki OrdinalEncoder ko 2D data (DataFrame) chahiye.

Difference samjho 👇

Single bracket:

df['Discount Band']

➡️ Ye Series deta hai → 1D

Low
Medium
High

Double bracket:

df[['Discount Band']]

➡️ Ye DataFrame deta hai → 2D

  Discount Band
0          Low
1       Medium
2          High
OrdinalEncoder ko kya chahiye?
oe.fit_transform(X)

Yahan X 2D hona chahiye, isliye:

oe.fit_transform(df[['Discount Band']])

✅ Correct

Whereas:

oe.fit_transform(df['Discount Band'])

❌ Usually error देगा क्योंकि ye 1D Series hai.

🧠 Easy trick

[] → Series (1D)
[[]] → DataFrame (2D)

Isliye Encoder ke input mein double brackets use kiye.

In [33]:
df['Discount Band']= oe.fit_transform(df[['Discount Band']])

df.isnull().sum().sum() ka simple meaning hai:

Puri DataFrame mein total kitni missing/NaN values hain, woh count karo.

Step-by-step 👇
df.isnull()

Har cell ko check karega:

Missing value → True
Value present → False

Example:

Name	Age
Rahul	20
NaN	25
Priya	NaN

Output:

Name   Age
False  False
True   False
False  True
1️⃣ First .sum()
df.isnull().sum()

Har column mein missing values count karega:

Name    1
Age     1
2️⃣ Second .sum()
df.isnull().sum().sum()

Ab jo column-wise counts aaye hain, unko add karega:

1 + 1 = 2

So output:

2
🧠 Easy way to remember
df.isnull()          # Missing hai ya nahi?
df.isnull().sum()    # Har column mein kitni missing?
df.isnull().sum().sum()  # Puri DataFrame mein total missing?

Real-life example:
Socho classroom mein 5 subjects hain. Pehla sum() batata hai har subject mein kitne students absent hain, aur doosra sum() batata hai total absences kitni hain.

In [34]:
df['Discount Band'].unique()

array([1., 2., 0.])

In [36]:
#OneHotEncoder
df['Country'].unique()

array(['Canada', 'Germany', 'France', 'Mexico',
       'United States of America'], dtype=object)

def oneHotEncoder(val):
    df[val] = df['Country'].map(lambda c: 1 if val == c else 0)
    return val

for name in df['Country'].unique():
    print(oneHotEncoder(name))
1. df['Country'].unique()
df['Country'].unique()

Country ki unique values nikalega, maan lo:

['India', 'USA', 'Canada']
2. for name in ...
for name in df['Country'].unique():

Har country ko ek-ek karke name mein lega:

name = 'India'
name = 'USA'
name = 'Canada'
3. Function oneHotEncoder(val)
def oneHotEncoder(val):

val mein current country aayega.

Example:

val = 'India'
4. Main logic
df[val] = df['Country'].map(lambda c: 1 if val == c else 0)

Ye Country ke har value ko check karta hai.

Example:

Agar:

val = 'India'

Aur Country column:

India
USA
Canada
India

To:

India → 1
USA   → 0
Canada → 0
India → 1

Isse ek naya column banega:

Country	India
India	1
USA	0
Canada	0
India	1

Phir next iteration:

val = 'USA'

Naya column:

Country	USA
India	0
USA	1
Canada	0
India	0

And similarly Canada.

5. lambda c
lambda c: 1 if val == c else 0

Yahan c Country column ki ek-ek value hai.

Simple language:

Agar current country (c) aur selected country (val) same hain → 1, warna → 0.

🧠 One-line meaning
1 if val == c else 0

means:

Same hai → 1, different hai → 0.

6. return val
return val

Function ke end mein country ka naam return karega.

Isliye:

print(oneHotEncoder(name))

Output:

India
USA
Canada
⚠️ Important correction

Aapke code mein:

df[val] = ...

ka matlab country ke naam se new column create karna hai.

So final DataFrame roughly:

Country	India	USA	Canada
India	1	0	0
USA	0	1	0
Canada	0	0	1

यही One-Hot Encoding hai.

Easy formula:

Category → Separate Column → Match = 1, No Match = 0.

In [39]:
#Apply OneHotEncoding(mannual -> Algorithm)
def oneHotEncoder(val):
    df[val] = df['Country'].map(lambda c : 1 if val==c else 0)
    return val

In [40]:
for name in df['Country'].unique():
    print(oneHotEncoder(name))

Canada
Germany
France
Mexico
United States of America

In [41]:
df.head(5)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,...,Profit,Date,Month Number,Month Name,Year,Canada,Germany,France,Mexico,United States of America
0,Government,Canada,Carretera,1.0,1618.5,3,20,32370.0,0.0,32370.0,...,16185.0,2014-01-01,1,January,2014,1,0,0,0,0
1,Government,Germany,Carretera,1.0,1321.0,3,20,26420.0,0.0,26420.0,...,13210.0,2014-01-01,1,January,2014,0,1,0,0,0
2,Midmarket,France,Carretera,1.0,2178.0,3,15,32670.0,0.0,32670.0,...,10890.0,2014-06-01,6,June,2014,0,0,1,0,0
3,Midmarket,Germany,Carretera,1.0,888.0,3,15,13320.0,0.0,13320.0,...,4440.0,2014-06-01,6,June,2014,0,1,0,0,0
4,Midmarket,Mexico,Carretera,1.0,2470.0,3,15,37050.0,0.0,37050.0,...,12350.0,2014-06-01,6,June,2014,0,0,0,1,0

In [62]:
from sklearn.preprocessing import OneHotEncoder

In [64]:
#ohe= OneHotEncoder()
ohe = OneHotEncoder(sparse_output=False)

In [65]:
outputs = ohe.fit_transform(df[['Country']])

In [66]:
outputs

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], shape=(700, 5))

In [68]:
import sklearn
print(sklearn.__version__)

1.9.0

In [69]:
print(outputs[ :5])

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

In [72]:
#print(outputs[ :5].toarray())

In [73]:
country_df = pd.DataFrame(outputs,columns=ohe.get_feature_names_out())

In [74]:
country_df

,Country_Canada,Country_France,Country_Germany,Country_Mexico,Country_United States of America
0,1.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...
695,0.0,1.0,0.0,0.0,0.0
696,0.0,0.0,0.0,1.0,0.0
697,0.0,0.0,0.0,1.0,0.0
698,1.0,0.0,0.0,0.0,0.0
699,0.0,0.0,0.0,0.0,1.0

In [75]:
from sklearn.preprocessing import LabelEncoder

In [76]:
le=LabelEncoder()

In [81]:
#output = le.fit_transform(df[['Profduct']])
output = le.fit_transform(df[['Product']])

c:\Users\dell\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [82]:
output

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4,
       4, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 5, 4, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5,
       4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 4,
       4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 4, 4, 4, 4, 4, 4, 1, 3, 5, 4,
       2, 3, 3, 5, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 5, 5, 5, 4, 4, 4, 4, 0, 0, 0, 0, 0, 2, 3, 3, 3, 3, 5, 4,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4,
       4, 4, 4, 4, 0, 0, 0, 0, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3,
       3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 2, 3, 3, 3,
       3, 5, 5, 4, 1, 1, 1, 2, 2, 3, 5, 5, 5, 5, 4, 4, 4, 0, 1, 1, 1, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4,
       0, 0, 0, 0, 0, 2, 2, 3, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 4, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0,
       1, 1, 1, 1, 3, 3, 3, 5, 5, 4, 4, 4, 0, 0, 0, 1, 2, 3, 1, 1, 2, 2,
       2, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4,
       4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 3, 5, 5, 4, 4, 0, 0, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 4, 4,
       4, 0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 1, 2,
       3, 4, 4, 0, 1, 4, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 0, 0, 0, 0, 1, 1, 1, 1,
       2, 2, 3, 3, 3, 3, 4, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 0, 0, 2, 3, 4])

1. Manual One-Hot Encoding

Aapne function banaya:

def oneHotEncoder(val):
    df[val] = df['Country'].map(lambda c: 1 if val == c else 0)
    return val

Iska purpose hai Country ke har category ka separate column banana.

Aapke dataset mein 5 countries hain:

Canada
Germany
France
Mexico
United States of America

Loop:

for name in df['Country'].unique():
    print(oneHotEncoder(name))

Har country ko one-by-one function mein bhej raha hai.

Example:

name = Canada

To:

df['Canada'] = df['Country'].map(
    lambda c: 1 if 'Canada' == c else 0
)

Result:

Canada → 1
Germany → 0
France → 0
Mexico → 0

Phir Germany ke liye:

Canada  → 0
Germany → 1
France  → 0
Mexico  → 0

Isi tarah 5 separate columns ban jaate hain.

2. Algorithm se One-Hot Encoding

Aapne ye import kiya:

from sklearn.preprocessing import OneHotEncoder

Phir:

ohe = OneHotEncoder(sparse_output=False)
sparse_output=False kya karta hai?

Normally encoder sparse matrix de sakta hai.

sparse_output=False

lagane se normal NumPy array milega:

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 ...]
3. fit_transform()
outputs = ohe.fit_transform(df[['Country']])

Yahan:

fit() → Encoder ko Country ki categories sikhata hai.

For example:

Canada
Germany
France
Mexico
United States of America

transform() → In categories ko 0 aur 1 mein convert karta hai.

So:

fit_transform()

= Fit + Transform ek saath.

4. outputs

Image mein aapko output kuch aisa mil raha hai:

[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 ...
]

Aur:

shape = (700, 5)

ka matlab:

700 rows × 5 encoded columns

Kyuki aapke Country mein 5 unique categories hain.

5. outputs[:5]

Aapne ye bhi kiya:

print(outputs[:5])

Iska meaning:

Outputs ki first 5 rows dikhao.

: ka matlab yahan start se hai.

So:

outputs[:5]

= row 0 se row 4 tak → first 5 rows.

🧠 Overall Flow

Aapke lecture mein basically ye comparison ho raha hai:

        Country
           ↓
   ┌───────────────┐
   │ Manual Method │
   └───────────────┘
           ↓
   lambda + map()
           ↓
     0 / 1 columns

Aur:

        Country
           ↓
   ┌─────────────────┐
   │ OneHotEncoder() │
   └─────────────────┘
           ↓
      fit_transform()
           ↓
       0 / 1 matrix
Sabse important difference

Manual:

df[val] = df['Country'].map(
    lambda c: 1 if val == c else 0
)

Aap khud logic bana rahe ho.

Algorithm:

ohe = OneHotEncoder(sparse_output=False)
outputs = ohe.fit_transform(df[['Country']])

sklearn ka OneHotEncoder automatically ye kaam karta hai.

👉 Isi wajah se algorithm wala method short, clean aur scalable hai.